pipeline {
	agent any
	stages {
		stage('Build') {
			steps {
				withEnv(["HOME=${env.WORKSPACE}"]) {
					sh '''
					python3 -m pip install --upgrade pip
					python3 -m pip install --upgrade venv
					python3 -m venv venv
					. venv/bin/activate
					python3 -m pip install -r requirements.txt
					'''
				}
			}
		}
	}
}
