pipeline {
	agent any
	stages {
		stage('Build') {
			steps {
				sh '''
				sudo apt-get install -y python3-venv
				python3 -m venv venv
				. venv/bin/activate
				python3 -m pip install -r requirements.txt
				'''
			}
		}
		stage('Deploy') {
			steps {
				ansiblePlaybook(
					credentialsId: 'trainer-vm-key',
					inventory: 'jenkins/inventory.yml',
					playbook: 'ansible/playbook_p0_1.yml',
					disableHostKeyChecking: true)
			}
		}
	}
}
