pipeline {
	agent none
	stages {
		stage('Build') {
			agent {
				docker {
					image 'python:3.6.13-slim-buster'
				}
			}
			steps {
				sh 'echo $HOME'
				with(["HOME=${env.WORKSPACE}"]) {
					sh '''
					pip install --upgrade pip
					pip install --upgrade venv
					python3 -m venv venv
					. venv/bin/activate
					pip install -r requirements.txt
					'''
				}
			}
		}
	}
}
