---
- hosts: virtual_machines
  become: true
  tasks:

  #- name: update repository
  #  apt:
  #    update_cache: yes

  - name: install git
    package:
      name: git
      state: latest
    become_user: root

  - name: install python3
    package:
      name: python3
      update_cache: yes

  - name: install python3-venv
    package:
      name: python3-venv
      state: latest
      update_cache: yes