---
- hosts: all
  become: true
  tasks:

  - name: update repository
    apt:
      update_cache: yes

  - name: install git
    ansible.builtin.package:
      name: git
      state: latest
      update_cache: yes

  - name: install python3
    ansible.builtin.package:
      name: python3
      update_cache: yes

  - name: install python3-venv
    ansible.builtin.package:
      name: python3-venv
      update_cache: yes