---
- hosts: virtual_machines
  gather_facts: false
  tasks:

  - name: Get project0 files
    git:
      repo: https://github.com/2105-may24-devops/moonjun-project0.git
      clone: yes
      force: yes
      dest: "~/p0/project0"
      

  - name: Create venv
    command:
      cmd: python3 -m venv /home/moonjun/venv
      creates: "/home/moonjun/venv"
  
  - name: Creating dummy files
    command:
      cmd: bash /home/moonjun/p0/project0/ansible/create_dummies.sh