---
- hosts: virtual_machines
  gather_facts: false
  become: true
  tasks:

  - name: Uninstall the project
    file:
      state: absent
      path: "~/p0"

  - file:
      state: absent
      path: "~/venv"